"""

modules/pluto/agents.py
LangGraph agents with improved state handling and validation.

"""




from typing import TypedDict, Dict, Any, Optional
from langgraph.graph import StateGraph, END

from .llm_client import LLMClient, OutputFormat
from .logging_config import get_logger

logger = get_logger(__name__)


class AgentState(TypedDict):
    ticker: str
    quant_score: float
    news_analysis: str
    fundamental_analysis: str
    risk_assessment: str
    final_recommendation: str
    confidence: Optional[float]


class LangGraphOrchestrator:
    def __init__(self, llm_client: LLMClient):
        """
        Initializes the LangGraph workflow with an LLM client.
        """
        self.llm = llm_client
        self.graph = self._build_graph()

    def _build_graph(self):
        workflow = StateGraph(AgentState)

        workflow.add_node("news_analyst", self.news_analyst)
        workflow.add_node("fundamental_analyst", self.fundamental_analyst)
        workflow.add_node("risk_manager", self.risk_manager)
        workflow.add_node("investment_committee", self.investment_committee)

        workflow.set_entry_point("news_analyst")
        workflow.add_edge("news_analyst", "fundamental_analyst")
        workflow.add_edge("fundamental_analyst", "risk_manager")
        workflow.add_edge("risk_manager", "investment_committee")
        workflow.add_edge("investment_committee", END)

        return workflow.compile()

    def news_analyst(self, state: AgentState) -> Dict[str, Any]:
        """Analyze news sentiment and return only updated fields."""
        ticker = state.get("ticker", "unknown")
        try:
            prompt = f"Read the latest unstructured news for {ticker} and summarize market sentiment."
            analysis = self.llm.generate(prompt, output_format=OutputFormat.TEXT)
            if not analysis:
                analysis = "News analysis unavailable"
        except Exception as e:
            logger.error("News analyst failed for %s: %s", ticker, e)
            analysis = "News analysis unavailable"
        return {"news_analysis": analysis}

    def fundamental_analyst(self, state: AgentState) -> Dict[str, Any]:
        """Analyze fundamentals and return only updated fields."""
        ticker = state.get("ticker", "unknown")
        try:
            prompt = f"Analyze balance sheets and company reports for {ticker}."
            analysis = self.llm.generate(prompt, output_format=OutputFormat.TEXT)
            if not analysis:
                analysis = "Fundamental analysis unavailable"
        except Exception as e:
            logger.error("Fundamental analyst failed for %s: %s", ticker, e)
            analysis = "Fundamental analysis unavailable"
        return {"fundamental_analysis": analysis}

    def risk_manager(self, state: AgentState) -> Dict[str, Any]:
        """Assess risk and return only updated fields."""
        ticker = state.get("ticker", "unknown")
        try:
            prompt = f"Evaluate macroeconomic risks and asset volatility for {ticker}."
            assessment = self.llm.generate(prompt, output_format=OutputFormat.TEXT)
            if not assessment:
                assessment = "Risk assessment unavailable"
        except Exception as e:
            logger.error("Risk manager failed for %s: %s", ticker, e)
            assessment = "Risk assessment unavailable"
        return {"risk_assessment": assessment}

    def investment_committee(self, state: AgentState) -> Dict[str, Any]:
        """Final decision with validation and confidence scoring."""
        ticker = state["ticker"]
        quant_score = state["quant_score"]
        news = state.get("news_analysis", "")
        fundamentals = state.get("fundamental_analysis", "")
        risk = state.get("risk_assessment", "")

        prompt = f"""
        Act as a final Investment Committee. Review the following data and debate the outcome:
        - Ticker: {ticker}
        - Statistical Quant Score: {quant_score} (Generated by XGBoost, DO NOT predict this)
        - News Sentiment: {news}
        - Fundamentals: {fundamentals}
        - Risk: {risk}

        Provide a final investment recommendation and explain your reasoning.
        Return a JSON with keys: "recommendation" (BUY/SELL/HOLD) and "reasoning" (string).
        """
        try:
            response = self.llm.generate(prompt, output_format=OutputFormat.JSON)
        except Exception as e:
            logger.error("Investment committee failed for %s: %s", ticker, e)
            response = {}

        # Validate recommendation
        valid = {"BUY", "SELL", "HOLD"}
        rec = response.get("recommendation", "HOLD").upper()
        if rec not in valid:
            rec = "HOLD"
        reasoning = response.get("reasoning", "No reasoning provided.")

        # Determine confidence based on quant score (capped at 0.95)
        confidence = min(quant_score, 0.95)
        # Optionally adjust confidence based on LLM output quality
        if not reasoning or len(reasoning) < 10:
            confidence *= 0.8

        final_recommendation = f"{rec} {ticker}. {reasoning}"

        logger.info(
            "Investment decision: %s for %s with confidence %.2f",
            rec, ticker, confidence
        )

        return {
            "final_recommendation": final_recommendation,
            "confidence": confidence,
        }

    def run_analysis(self, ticker: str, quant_score: float) -> str:
        """Run the full workflow and return the final recommendation string."""
        initial_state: AgentState = {
            "ticker": ticker,
            "quant_score": quant_score,
            "news_analysis": "",
            "fundamental_analysis": "",
            "risk_assessment": "",
            "final_recommendation": "",
            "confidence": None,
        }
        final_state = self.graph.invoke(initial_state)
        return final_state["final_recommendation"]